### ISSUE TITLE
Possible issue with the release flag on Keyboard.press

### ISSUE THREAD

**Issue by witnessmenow** [atc1441/CH_HID_Arduino#1]
I tested using the keyboard.press with the release flag and it didn't seem to work as expected

Sending in the message "Hello" produced the following output on my Windows 10 machine "HHEHELHELHELO", here was the code I used.
```
        String str = bot.messages[i].text;
        // Length (with one extra character for the null terminator)
        int str_len = str.length() + 1;

        // Prepare the character array (the buffer)
        char char_array[str_len];

        // Copy it over
        str.toCharArray(char_array, str_len);
        for(int j = 0; j < str.length(); j++)
        {
          Keyboard.press(char_array[j], true);
          delay(100);
        }
```

The same test with the following code worked as expected

```
        String str = bot.messages[i].text;
        // Length (with one extra character for the null terminator)
        int str_len = str.length() + 1;

        // Prepare the character array (the buffer)
        char char_array[str_len];

        // Copy it over
        str.toCharArray(char_array, str_len);
        for(int j = 0; j < str.length(); j++)
        {
          Keyboard.press(char_array[j]);
          delay(50);
          Keyboard.release(char_array[j]);
          delay(50);
        }
```

**Comment by atc1441** [comment]
This boolean is used internally in the CH552 to release the key on its own, the library still thinks the key is pressed so you need to still do a release but with a false flag at the end so the it will only release the key in the library itself and not send a command to the CH552

Use this:
```
          Keyboard.press(char_array[j], true);
          Keyboard.release(char_array[j], false);
```

But better is to just use this, it will do internally the same as the above but already in the library implemented so you can not forgot to release the key after pressing it
`          Keyboard.write(char_array[j]);`
